### PR TITLE
Manually set and constant tau, r_on and s

### PR DESCRIPTION
**Pull request by jamessergeant**
As per the lip reading experiment in the original paper, have added an input argument to allow for manually setting constant (non-trainable) values of tau, r_on and s. Additionally, a hard gating is applied during r_on. #6

### CODE REVIEW

**Comment by Enny1991** [comment]
Hey @jamessergeant, 
I think is a nice add-on to put non trainable parameters! 
But I'm not sure why can't we just set the `trainable=False`? Why would you set the initialization to constant? In this way all the units will have the same parameters. I would leave it initialize as it was before and just set the trainable to false.
What do you think?

+Enea

**Comment by jamessergeant** [comment]
@Enny1991, in the paper they manually set the period (and I presumed r_on and s, will need to double check the paper) to constants to match the input frequencies of the audio and video streams. I could separate this functionality using another input arg.

**Comment by Enny1991** [comment]
Yeah I would rather do that. Maybe have the choice between not train the parameters and set them to a precise value.
Someone might want to not train but still have some variability in the different units.

**Comment by jamessergeant** [comment]
Sounds good. I'll modify tomorrow and update my fork.

**Comment by jamessergeant** [comment]
@Enny1991 Have updated with the discussed change.

**Comment by jamessergeant** [comment]
Hi @Enny1991 just though I'd follow up on this.

**Comment by Enny1991** [comment]
Yup, sorry for the delay!

**Comment by jamessergeant** [comment]
Thanks @Enny1991 :) Cheers for the implementation btw. Is coming in very handy.

**Pull request merged**
